<?php

namespace AppBundle\Repository;

/**
 * check_transactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class check_transactionRepository extends \Doctrine\ORM\EntityRepository
{
}
