<?php

namespace AppBundle\Repository;

/**
 * ChequeTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChequeTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
